// const ON_LOGIN_FORM_CHANGE="ON_LOGIN_FORM_CHANGE";
// const ON_LOGIN_FORM_SUBMIT = "ON_LOGIN_FORM_SUBMIT"
module.exports= {  ON_LOGIN_FORM_CHANGE:"ON_LOGIN_FORM_CHANGE",
                    ON_LOGIN_FORM_SUBMIT:"ON_LOGIN_FORM_SUBMIT",
                    SET_STORAGE_DATA:"SET_STORAGE_DATA",
                    GET_STORAGE_DATA:"GET_STORAGE_DATA",
                    SET_DEFECT_PRIORITY:"SET_DEFECT_PRIORITY",
                    SET_DEFECT_CATEGORY:"SET_DEFECT_CATEGORY",
                    SET_DEFECT_DATA:"SET_DEFECT_DATA",
                    SET_ORIGINAL_DATA:"SET_ORIGINAL_DATA",
                    SET_DEFECT: "SET_DEFECT",
                    SET_DEFECT_CATEGORY_DATA: "SET_DEFECT_CATEGORY_DATA",
                    SET_DEFECT_PRIORITY_DATA: "SET_DEFECT_PRIORITY_DATA",
                    SET_DESCRIPTION_DATA: "SET_DESCRIPTION_DATA"
                }